// Block generator: plans the next block from a learned Template and an AthleteModel (see GENERATOR.md).
// Pure and deterministic: no DOM, no storage, no randomness (a string seed drives every choice) and no clock
// apart from the default `now`. All maths in kg. A planning aid, not coaching advice: everything stays editable.
import { pctSmooth } from './rpe-chart.js';
import { roundToStep } from './attempts.js';
import { toKg, round1 } from './units.js';

const FAMILIES = ['squat', 'bench', 'deadlift'];
const FOCUSES = ['strength', 'volume', 'peak', 'deload', 'maintenance', 'return', 'specialise'];
const DRIFT = { conservative: 0.002, standard: 0.004, aggressive: 0.006 };
const DELOAD_WEEKS = ['none', 'last', 'all'];
const STANCE_SWAPS = {
  sumo: { conventional_deadlift: 'sumo_deadlift', deadlift: 'sumo_deadlift', tempo_to_knee_deadlift: 'tempo_to_knee_sumo_deadlift' },
  conventional: { sumo_deadlift: 'conventional_deadlift', deadlift: 'conventional_deadlift', tempo_to_knee_sumo_deadlift: 'tempo_to_knee_deadlift' },
};
const CHECKED_MUSCLES = ['chest', 'quads', 'hamstrings', 'glutes', 'lats', 'upper_back', 'triceps', 'biceps', 'lower_back'];
const FIND_LOAD = 'Find a load that reaches the target effort inside the rep range.';
const TOP_OF_RANGE = 'When every set reaches the top of the rep range, go up one step next week.';
const INSTRUCTIONS = 'Generated by the app from your recent training. Every number is a suggestion: change anything that does not fit.';
const GOALS = {
  strength: 'Build strength on the competition lifts with a gradual rise in effort.',
  volume: 'Build work capacity and muscle with extra sets at moderate effort.',
  peak: 'Bring strength to a peak with the heaviest work in the final full week.',
  deload: 'Recover: fewer sets at lower effort.',
  maintenance: 'Hold current strength with less fatigue and less time in the gym.',
  return: 'Rebuild after a layoff, starting lighter and working back to full loads.',
  specialise: 'Bring up one lift while the others keep ticking over.',
};

const hasOwn = (o, k) => o != null && Object.prototype.hasOwnProperty.call(o, k);
const title = (s) => s[0].toUpperCase() + s.slice(1);
const clamp = (x, lo, hi) => Math.min(hi, Math.max(lo, x));
const chartReps = (reps) => (Array.isArray(reps) ? reps[0] : reps);
const copyReps = (reps) => (Array.isArray(reps) ? [...reps] : reps ?? null);
const easeRpe = (rpe) => (rpe === 11 ? 9 : rpe === 9 ? 8 : rpe);
const fail = (message) => { throw new RangeError(message); };

/** 32-bit FNV-1a hash of the UTF-8 bytes of `str`, as an unsigned integer. */
export function fnv1a(str) {
  let h = 0x811c9dc5;
  for (const byte of new TextEncoder().encode(String(str))) h = Math.imul(h ^ byte, 0x01000193) >>> 0;
  return h;
}

function drift(progression, focus) {
  if (!hasOwn(DRIFT, progression)) fail(`progression must be one of: ${Object.keys(DRIFT).join(', ')}`);
  if (focus === 'maintenance' || focus === 'return') return 0;
  return DRIFT[progression] * (focus === 'volume' ? 0.75 : 1);
}

/**
 * E(f, w): projected e1RM in week `week` (1-based). Focus `return` ramps from the start fraction to 100% by the
 * last week and needs `weeks` and `layoffWeeks`; every other focus drifts by g per week. Null when e1RM unknown.
 */
export function projectedE1rm(athleteE1rm, progression, focus, week, { weeks = week, layoffWeeks = 4 } = {}) {
  const g = drift(progression, focus);
  if (!Number.isFinite(athleteE1rm) || athleteE1rm <= 0) return null;
  if (focus === 'return') {
    const s = Math.max(0.8, 1 - 0.01 * layoffWeeks);
    return athleteE1rm * (weeks <= 1 ? s : s + ((1 - s) * (week - 1)) / (weeks - 1));
  }
  return athleteE1rm * (1 + g) ** (week - 1);
}

function e1rmOf(athlete, family) {
  const v = athlete.lifts?.[family]?.e1rmKg;
  return FAMILIES.includes(family) && Number.isFinite(v) && v > 0 ? v : null;
}

function biasOf(athlete, family) {
  const b = athlete.rpeBias?.[family];
  return Number.isFinite(b) ? clamp(b, -0.5, 0.5) : 0;
}

// The load of an all-out (RPE 10) set for these reps at the athlete's current e1RM: no planned set goes above it.
function ceilingKg(current, reps) {
  const pct = pctSmooth(chartReps(reps), 10);
  return current == null || pct == null ? Infinity : current * pct;
}

// Round to the plate step, but never above the ceiling (rounding to nearest could push a capped load over it).
function settle(value, ceiling) {
  const v = roundToStep(value);
  return v > ceiling ? roundToStep(Math.floor(ceiling / 2.5 + 1e-9) * 2.5) : v;
}

// E * pctSmooth(reps, rpePlan - bias) * k, before back-off and rounding; null when anything is missing.
// `current` is the athlete's e1RM now: projected weeks and a template k above 1 never plan beyond an all-out set at it.
function unrounded(e, reps, rpe, bias, k, current = e) {
  if (e == null || !Number.isFinite(k) || !Number.isFinite(rpe)) return null;
  const pct = pctSmooth(chartReps(reps), clamp(rpe - bias, 6, 10));
  if (pct == null) return null;
  return Math.min(e * pct * k, ceilingKg(current, reps));
}

function resolve(opts) {
  const { catalogue, template, athlete } = opts ?? {};
  if (!catalogue || !Array.isArray(catalogue.exercises)) fail('catalogue is required (data/exercises.json)');
  if (!template || !Array.isArray(template.days)) fail('template is required (from learnTemplate)');
  if (!athlete || !athlete.lifts || typeof athlete.lifts !== 'object') fail('athlete is required (from buildAthleteModel)');
  const templateDays = template.days.filter((d) => d?.slots?.length).length;
  if (!templateDays) fail('template has no days with exercises');
  const { blockNumber, focus = 'strength', emphasis = null, layoffWeeks = 4, checkIn = true, progression = 'standard',
    seed = 'seed', now = () => new Date(), name = null } = opts;
  if (!Number.isInteger(blockNumber) || blockNumber < 1) fail('blockNumber must be a positive integer');
  if (!FOCUSES.includes(focus)) fail(`focus must be one of: ${FOCUSES.join(', ')}`);
  if (emphasis !== null && !FAMILIES.includes(emphasis)) fail('emphasis must be squat, bench, deadlift or null');
  if (focus === 'specialise' && emphasis === null) fail('focus "specialise" needs an emphasis: squat, bench or deadlift');
  if (!Number.isInteger(layoffWeeks) || layoffWeeks < 1 || layoffWeeks > 52) fail('layoffWeeks must be an integer from 1 to 52');
  if (typeof checkIn !== 'boolean') fail('checkIn must be true or false');
  if (!hasOwn(DRIFT, progression)) fail(`progression must be one of: ${Object.keys(DRIFT).join(', ')}`);
  const weeks = opts.weeks ?? (focus === 'maintenance' || focus === 'return' ? 4 : clamp(template.weeksInBlock, 3, 8));
  if (!Number.isInteger(weeks) || weeks < 1 || weeks > 52) fail('weeks must be an integer from 1 to 52');
  const daysPerWeek = opts.daysPerWeek ?? (focus === 'maintenance' ? Math.min(3, templateDays) : templateDays);
  if (!Number.isInteger(daysPerWeek) || daysPerWeek < 1 || daysPerWeek > 7) fail('daysPerWeek must be an integer from 1 to 7');
  const rotate = opts.rotate ?? (focus === 'maintenance' ? 0.5 : 0.3);
  if (typeof rotate !== 'number' || !(rotate >= 0 && rotate <= 1)) fail('rotate must be a number from 0 to 1');
  const deloadWeek = opts.deloadWeek
    ?? (focus === 'deload' ? 'all' : focus === 'maintenance' || focus === 'return' ? 'none' : weeks >= 6 ? 'last' : 'none');
  if (!DELOAD_WEEKS.includes(deloadWeek)) fail(`deloadWeek must be one of: ${DELOAD_WEEKS.join(', ')}`);
  if (focus === 'deload' && deloadWeek !== 'all') fail('a deload block is a deload every week: leave deloadWeek unset or use "all"');
  const deadliftStance = opts.deadliftStance === undefined ? athlete.lifts.deadlift?.stance ?? null : opts.deadliftStance;
  if (deadliftStance !== null && !hasOwn(STANCE_SWAPS, deadliftStance)) fail('deadliftStance must be sumo, conventional or null');
  if (typeof now !== 'function') fail('now must be a function returning a Date');
  return { catalogue, template, athlete, blockNumber, focus, emphasis: focus === 'specialise' ? emphasis : null, layoffWeeks,
    checkIn, progression, weeks, daysPerWeek, rotate, deloadWeek, deadliftStance, seed: String(seed), now, name };
}

function copySlot(s, byId) {
  const ex = byId.get(s.exerciseId);
  const lift = Boolean(ex) && s.role !== 'accessory';
  return {
    slotId: s.slotId, exerciseId: s.exerciseId ?? null, name: ex ? ex.name : s.name,
    supersetGroup: s.supersetGroup ?? null, tempo: s.tempo ?? null, cues: [...(s.cues ?? [])],
    role: ex ? s.role : 'accessory', family: lift ? s.family : null, scheme: lift ? s.scheme : 'accessory',
    sets: s.sets, reps: copyReps(s.reps), rpe: s.rpe ?? null, loadKg: s.loadKg ?? null, k: lift ? s.k ?? null : null, primary: false,
  };
}

// Primary exposure per family: the main slot with the lowest reps (ties: highest rpe, then earliest day/slot).
// Families that already have a primary keep it, so a re-run after dropping days only fills the gaps.
function markPrimaries(days) {
  const slots = days.flatMap((d) => d.slots);
  const repsKey = (s) => (Number.isFinite(chartReps(s.reps)) ? chartReps(s.reps) : Infinity);
  const rpeKey = (s) => (Number.isFinite(s.rpe) ? s.rpe : -Infinity);
  for (const f of FAMILIES) {
    if (slots.some((s) => s.primary && s.family === f)) continue;
    let best = null;
    for (const s of slots) {
      if (s.role !== 'main' || s.family !== f) continue;
      if (!best || repsKey(s) < repsKey(best) || (repsKey(s) === repsKey(best) && rpeKey(s) > rpeKey(best))) best = s;
    }
    if (best) best.primary = true;
  }
}

// GENERATOR.md "maintenance" steps 1-4. Reductions never add sets (min(sets, ...)).
function reduceForMaintenance(days, byId) {
  const secondaryKept = new Set(), variationKept = new Set();
  for (const d of days) {
    const accessories = d.slots.filter((s) => s.role === 'accessory');
    const keep = new Set(), patterns = new Set();
    for (const s of accessories) {
      const p = byId.get(s.exerciseId)?.pattern;
      if (p && !patterns.has(p) && keep.size < 3) { patterns.add(p); keep.add(s); }
    }
    for (const s of accessories) if (keep.size < 3) keep.add(s);
    d.slots = d.slots.filter((s) => {
      if (s.role === 'main') {
        if (s.primary) return true;
        if (secondaryKept.has(s.family)) return false;
        secondaryKept.add(s.family);
        return true;
      }
      if (s.role === 'variation') {
        if (variationKept.has(s.family)) return false;
        variationKept.add(s.family);
        return true;
      }
      return keep.has(s);
    });
    for (const s of d.slots) {
      if (s.role === 'variation') s.sets = Math.min(s.sets, Math.max(2, Math.round(s.sets * 0.5)));
      else if (s.role === 'main' && s.scheme === 'singles') s.sets = Math.min(s.sets, 2);
      else if (s.role === 'main') {
        s.sets = Math.min(s.sets, Math.max(2, Math.round(s.sets * 0.67)));
        s.reps = Array.isArray(s.reps) ? s.reps.map((r) => Math.min(r, 3)) : s.reps == null ? null : Math.min(s.reps, 3);
      } else {
        s.sets = Math.max(1, s.sets - 1);
        s.rpe = easeRpe(s.rpe);
      }
    }
  }
}

function dropDays(days, target, byId, lines) {
  const weight = { main: 3, variation: 2 };
  const score = (d) => d.slots.reduce((t, s) => t + (weight[s.role] ?? 1), 0);
  const patternOf = (s) => byId.get(s.exerciseId)?.pattern ?? null;
  while (days.length > target) {
    let victim = days[0];
    for (const d of days) if (score(d) < score(victim) || (score(d) === score(victim) && d.number > victim.number)) victim = d;
    days = days.filter((d) => d !== victim);
    lines.push({ scope: 'day', text: `Dropped template day ${victim.number} (the lowest training priority) to fit ${target} days a week.` });
    for (const s of victim.slots) {
      if (s.role !== 'accessory') continue;
      const p = patternOf(s);
      if (p && days.some((d) => d.slots.some((x) => patternOf(x) === p))) {
        lines.push({ scope: 'slot', text: `Left out ${s.name} from dropped day ${victim.number}: its movement pattern is still trained on another day.` });
        continue;
      }
      const dest = days.reduce((a, d) => (d.slots.length < a.slots.length ? d : a));
      if (p && dest.slots.length < 7) {
        dest.slots.push(s);
        lines.push({ scope: 'slot', text: `Moved ${s.name} from dropped day ${victim.number} to template day ${dest.number} so its movement pattern is still trained.` });
      } else {
        lines.push({ scope: 'slot', text: `Left out ${s.name} from dropped day ${victim.number}: no day had room for it.` });
      }
    }
  }
  return days;
}

function swapStance(days, stance, byId, lines) {
  for (const d of days) for (const s of d.slots) {
    if (s.family !== 'deadlift' || !hasOwn(STANCE_SWAPS[stance], s.exerciseId)) continue;
    const to = byId.get(STANCE_SWAPS[stance][s.exerciseId]);
    if (!to) continue;
    lines.push({ scope: 'slot', text: `${s.name} becomes ${to.name} to match your ${stance} stance.` });
    s.exerciseId = to.id;
    s.name = to.name;
  }
}

function rotateAccessories(days, o, byId, lines) {
  const pool = days.flatMap((d) => d.slots).filter((s) => s.role === 'accessory' && byId.get(s.exerciseId)?.pattern);
  const count = Math.ceil(o.rotate * pool.length - 1e-9); // 0.7 * 10 is 7.000000000000001 in floating point
  const chosen = pool.map((s) => ({ s, h: fnv1a(o.seed + s.slotId) })).sort((a, b) => a.h - b.h).slice(0, count);
  const used = new Set(days.flatMap((d) => d.slots.map((s) => s.exerciseId)));
  const history = o.athlete.exercises ?? {};
  const lastDate = (e) => (hasOwn(history, e.id) ? history[e.id]?.lastDate ?? '' : null); // null = not done in 16 weeks
  for (const { s } of chosen) {
    const pattern = byId.get(s.exerciseId).pattern;
    const candidates = o.catalogue.exercises.filter((e) => e.pattern === pattern && e.id !== s.exerciseId && !e.lift && !used.has(e.id));
    if (!candidates.length) continue;
    // Never done first, then the oldest lastDate; the stable sort keeps catalogue order for ties.
    const pick = candidates.sort((a, b) => {
      const la = lastDate(a), lb = lastDate(b);
      if (la === null || lb === null) return (la === null ? 0 : 1) - (lb === null ? 0 : 1);
      return la < lb ? -1 : la > lb ? 1 : 0;
    })[0];
    used.add(pick.id);
    lines.push({ scope: 'slot', text: `${s.name} rotated to ${pick.name} (same movement pattern) for variety.` });
    s.exerciseId = pick.id;
    s.name = pick.name;
    s.loadKg = null; // the load then comes from the athlete's history for the new exercise, else blank
  }
}

function plannedSet(index, reps, rpe, value, gen) {
  const range = Array.isArray(reps);
  const lo = range ? reps[0] : reps ?? null, hi = range ? reps[1] : reps ?? null;
  return {
    index, repsMin: lo, repsMax: hi, repsRaw: lo == null ? null : range ? `${lo}-${hi}` : String(lo), targetRpe: rpe ?? null,
    load: value == null ? null : { value, unit: 'kg', raw: String(value) }, loadRange: null,
    actualRpe: null, actualReps: null, actualLoad: null, coachComment: null, athleteComment: null,
    completed: false, source: { sheet: 'generated', row: 0, col: 0 }, warnings: [], gen,
  };
}

function liftSets(s, w, c) {
  const n = c.weeks, f = s.family, deload = c.isDeload(w), finalFull = w === c.finalFull;
  const exposure = s.role === 'main' ? (s.primary ? 'primary' : 'secondary') : c.famHasPrimary.has(f) ? 'primary' : 'secondary';
  const r0 = s.rpe == null || s.rpe > 9 ? 7 : s.rpe;
  let rpe;
  if (exposure === 'secondary') rpe = Math.min(7, r0);
  else if (c.focus === 'maintenance') rpe = 7.5;
  else if (c.focus === 'return') rpe = Math.min(8, Math.max(6, r0 - 1) + 0.5 * (w - 1));
  else if (s.scheme === 'singles') {
    rpe = w <= 2 ? 8 : w <= 4 ? 8.5 : 9;
    if (c.focus === 'peak' && finalFull) rpe = 9;
    if (c.focus === 'volume') rpe = Math.min(8.5, rpe);
  } else if (c.focus === 'volume') rpe = Math.min(8, r0);
  else {
    rpe = Math.min(8.5, r0 + 1, r0 + 0.5 * (w - 1));
    if (c.focus === 'peak' && finalFull) rpe = Math.min(9, rpe + 0.5);
  }

  let sets = s.sets;
  const mid = w >= 2 && w <= n - 1;
  const addSet = (x) => ((s.scheme === 'straight' || s.scheme === 'top-backoff') && x < 6 ? x + 1 : x);
  if (c.focus === 'return' && w <= 2) sets = Math.min(sets, Math.max(2, sets - 1));
  if (c.focus === 'volume' && mid) sets = addSet(sets);
  if (c.focus === 'specialise') {
    if (f === c.emphasis) { if (mid) sets = addSet(sets); } else if (s.role === 'variation') sets = Math.max(1, sets - 1);
  }
  if (c.focus === 'peak' && finalFull && s.role === 'variation') sets = Math.max(1, sets - 1);
  if (deload) {
    sets = Math.max(1, Math.round(sets * 0.6));
    rpe = s.scheme === 'singles' ? 7 : Math.max(6, rpe - 1);
  }

  const e = exposure === 'secondary' ? c.E(f, 1) : c.E(f, deload ? Math.max(1, w - 1) : w);
  const k = Number.isFinite(s.k) ? s.k : s.role === 'main' ? 1 : null;
  const bias = biasOf(c.athlete, f);
  const current = c.e1rmStart[f];
  const base = unrounded(e, s.reps, rpe, bias, k, current);
  const checkIn = c.focus === 'maintenance' && c.checkIn && n >= 3 && w === n && !deload && s.role === 'main' && s.primary;
  const out = [];
  for (let i = 0; i < sets; i++) {
    let kind = s.scheme === 'top-backoff' ? (i === 0 ? 'top' : 'backoff') : s.scheme === 'singles' ? 'single' : 'straight';
    let reps = s.reps, setRpe = rpe;
    let value = base == null ? null : base * (kind === 'backoff' ? 1 - 0.03 * i : 1);
    if (checkIn && i === 0) { kind = 'top'; reps = 1; setRpe = 8; value = unrounded(e, 1, 8, bias, k, current); }
    if (value != null) { value = settle(value, ceilingKg(current, reps)); c.loaded.add(f); }
    out.push(plannedSet(i + 1, reps, setRpe, value,
      { slotId: s.slotId, kind, family: f, reps: copyReps(reps), rpe: setRpe, e1rmRef: e == null ? null : round1(e), k, week: w, exposure }));
  }
  return out;
}

function accessoryEntry(s, w, c) {
  let sets = s.sets, rpe = s.rpe;
  if (c.focus === 'return' && w <= 2) sets = Math.max(1, sets - 1);
  if (c.focus === 'peak' && w === c.finalFull) sets = Math.max(1, sets - 1);
  if (c.isDeload(w)) { sets = Math.max(1, sets - 1); rpe = easeRpe(rpe); }
  const history = c.athlete.exercises ?? {};
  const last = s.exerciseId != null && hasOwn(history, s.exerciseId) ? history[s.exerciseId]?.lastWeightKg : null;
  const value = Number.isFinite(last) ? last : Number.isFinite(s.loadKg) ? s.loadKg : null;
  const cues = [...s.cues];
  if (Array.isArray(s.reps)) cues.push(TOP_OF_RANGE);
  if (value == null) cues.push(FIND_LOAD);
  const out = [];
  for (let i = 0; i < sets; i++) {
    out.push(plannedSet(i + 1, s.reps, rpe, value,
      { slotId: s.slotId, kind: 'accessory', family: null, reps: copyReps(s.reps), rpe, e1rmRef: null, k: null, week: w, exposure: null }));
  }
  return { cues: [...new Set(cues)], sets: out };
}

function entryFor(s, w, c) {
  const { cues, sets } = s.role === 'accessory' ? accessoryEntry(s, w, c) : { cues: [...s.cues], sets: liftSets(s, w, c) };
  return { exerciseId: s.exerciseId, name: s.name, rawName: s.name, supersetGroup: s.supersetGroup, tempo: s.tempo, cues, sets };
}

// Weekly hard sets per muscle (primary 1, secondary 0.5 per set by default), like core/muscles.js.
function muscleSets(items, catalogue, byId) {
  const weights = catalogue.weights ?? { primary: 1, secondary: 0.5 };
  const muscles = Object.fromEntries((catalogue.muscles ?? []).map((m) => [m, 0]));
  for (const { exerciseId, sets } of items) {
    const ex = byId.get(exerciseId);
    if (!ex || !Number.isFinite(sets)) continue;
    for (const role of ['primary', 'secondary']) for (const m of ex[role] ?? []) if (hasOwn(muscles, m)) muscles[m] += sets * weights[role];
  }
  return muscles;
}

function blockRationale(o, c, slots, athlete) {
  const out = [];
  for (const f of FAMILIES) {
    const lift = athlete.lifts[f];
    if (c.e1rmStart[f] != null) out.push({ scope: 'block', text: `${title(f)} e1RM ${c.e1rmStart[f].toFixed(1)} kg${lift?.basis ? `: ${lift.basis}` : ''}` });
  }
  const n = o.weeks;
  const span = n >= 3 ? `weeks 2 to ${n - 1}` : 'no weeks (the block is too short)';
  if (o.focus === 'maintenance') {
    out.push({ scope: 'block', text: 'Maintenance: about a third fewer main-lift sets, accessories down by one set, intensity kept (top sets at RPE 7.5). '
      + `The aim is to hold your e1RM${o.checkIn && n >= 3 ? `; week ${n} turns each main lift's top set into a single at RPE 8 as the check-in` : ''}.` });
    out.push({ scope: 'block', text: 'No projected gain: every week uses your current e1RM.' });
  } else if (o.focus === 'return') {
    const s = Math.max(0.8, 1 - 0.01 * o.layoffWeeks);
    out.push({ scope: 'block', text: `Return after ${o.layoffWeeks} weeks off: week 1 uses ${Math.round(s * 100)}% of your e1RM and climbs evenly to 100% by week ${n}, `
      + 'so the body can catch up with the loads. Main-lift RPE starts 1 below the template (at least 6) and rises 0.5 a week to at most 8; weeks 1 and 2 have one set fewer.' });
  } else {
    if (o.focus === 'volume') out.push({ scope: 'block', text: `Volume: main lifts stay at the template RPE (at most 8) and gain one set in ${span} (never above 6 sets).` });
    else if (o.focus !== 'deload') out.push({ scope: 'block', text: 'Wave: main-lift RPE rises 0.5 a week from the template RPE, at most 1 above it and never above 8.5; singles go RPE 8, 8.5, then 9 from week 5.' });
    if (o.focus === 'peak' && c.finalFull) out.push({ scope: 'week', text: `Peak: week ${c.finalFull} is the heaviest week (0.5 RPE up, at most 9; singles at 9), with one set fewer on variations and accessories.` });
    if (o.focus === 'specialise') out.push({ scope: 'block', text: `Specialising in ${o.emphasis}: ${o.emphasis} main and variation slots gain one set in ${span} (never above 6); the other lifts' variations lose one set.` });
    const g = drift(o.progression, o.focus);
    out.push({ scope: 'block', text: `Projected e1RM rises ${+(g * 100).toFixed(3)}% a week (${o.progression} progression).` });
  }
  if (slots.some((s) => s.role === 'main' && !s.primary)) out.push({ scope: 'block', text: 'Other main-lift slots of the same lift hold RPE 7 at week-1 loads for the whole block.' });
  const present = new Set(slots.map((s) => s.family).filter(Boolean));
  for (const f of FAMILIES) {
    const eff = biasOf(athlete, f);
    if (!eff || !present.has(f)) continue;
    out.push({ scope: 'block', text: `${title(f)}: you usually rate sets ${Math.abs(eff)} RPE ${eff < 0 ? 'below' : 'above'} the target, `
      + `so loads are worked out as if the target were ${Math.abs(eff)} ${eff < 0 ? 'higher' : 'lower'}.` });
  }
  if (o.deloadWeek === 'all') out.push({ scope: 'block', text: 'Every week is a deload: about 40% fewer sets at 1 RPE lower, singles at RPE 7, no further e1RM drift.' });
  if (o.deloadWeek === 'last') out.push({ scope: 'week', text: `Week ${n} is a deload: about 40% fewer sets at 1 RPE lower, singles at RPE 7, no further e1RM drift.` });
  return out;
}

/**
 * Generate the next block. See GENERATOR.md for every option and rule.
 * @returns {{ block, rationale: {scope, text}[], warnings: string[], volume: { perWeek: {week, muscles}[], typical } }}
 */
export function generateBlock(options) {
  const o = resolve(options);
  const { catalogue, template, athlete, focus, weeks } = o;
  const byId = new Map(catalogue.exercises.map((e) => [e.id, e]));
  const lines = [], warnings = [];

  // Template -> working slots: reductions, day dropping, stance, rotation (GENERATOR.md order).
  let days = template.days.filter((d) => d?.slots?.length).map((d) => ({ number: d.number, slots: d.slots.map((s) => copySlot(s, byId)) }));
  markPrimaries(days);
  if (focus === 'maintenance') reduceForMaintenance(days, byId);
  if (o.daysPerWeek > days.length) warnings.push(`${o.daysPerWeek} days a week asked for, but the template has ${days.length}: keeping ${days.length} days.`);
  days = dropDays(days, o.daysPerWeek, byId, lines);
  markPrimaries(days);
  days.forEach((d, i) => { d.number = i + 1; });
  if (o.deadliftStance) swapStance(days, o.deadliftStance, byId, lines);
  rotateAccessories(days, o, byId, lines);
  const slots = days.flatMap((d) => d.slots);

  const e1rmStart = Object.fromEntries(FAMILIES.map((f) => [f, e1rmOf(athlete, f)]));
  const confidence = Object.fromEntries(FAMILIES.map((f) => [f, athlete.lifts[f]?.confidence ?? 'none']));
  const c = {
    ...o, e1rmStart, loaded: new Set(),
    famHasPrimary: new Set(slots.filter((s) => s.primary).map((s) => s.family)),
    isDeload: (w) => o.deloadWeek === 'all' || (o.deloadWeek === 'last' && w === weeks),
    finalFull: o.deloadWeek === 'all' ? 0 : o.deloadWeek === 'last' ? weeks - 1 : weeks,
    E: (f, w) => (e1rmStart[f] == null ? null : projectedE1rm(e1rmStart[f], o.progression, focus, w, { weeks, layoffWeeks: o.layoffWeeks })),
  };

  const weekList = [];
  for (let w = 1; w <= weeks; w++) {
    const deload = c.isDeload(w);
    const target = {}, parts = [];
    let total = null;
    for (const f of FAMILIES) {
      const e = c.E(f, deload ? Math.max(1, w - 1) : w);
      target[f] = e == null ? null : roundToStep(e);
      if (target[f] != null) total = (total ?? 0) + target[f];
      parts.push(target[f] == null ? '-' : String(target[f]));
    }
    target.total = total;
    const label = deload ? `Week ${w} - Deload` : total == null ? `Week ${w}` : `Week ${w} - ${parts.join('/')} [${total}kg]`;
    weekList.push({ number: w, label, target, avgCalories: null, avgBodyweightKg: null, bodyLog: [],
      days: days.map((d) => ({ number: d.number, entries: d.slots.map((s) => entryFor(s, w, c)) })) });
  }

  const perWeek = weekList.map((wk) => ({ week: wk.number,
    muscles: muscleSets(wk.days.flatMap((d) => d.entries.map((e) => ({ exerciseId: e.exerciseId, sets: e.sets.length }))), catalogue, byId) }));
  const typical = muscleSets(template.days.flatMap((d) => (d?.slots ?? []).map((s) => ({ exerciseId: s.exerciseId, sets: s.sets }))), catalogue, byId);
  if (focus !== 'maintenance') {
    const w2 = perWeek[Math.min(2, weeks) - 1].muscles;
    for (const [m, x] of Object.entries(typical)) {
      if (x >= 4 && Math.abs(w2[m] - x) > 0.25 * x) warnings.push(`${m.replace(/_/g, ' ')} volume changes from ${x} to ${w2[m]} sets per week`);
    }
    for (const m of CHECKED_MUSCLES) if ((w2[m] ?? 0) < 6) warnings.push(`${m.replace(/_/g, ' ')} is under 6 hard sets per week`);
  }
  for (const f of FAMILIES) {
    if (e1rmStart[f] == null) warnings.push(`No ${f} e1RM: ${f} loads are left blank. Log some ${f} sets with an RPE, or fill the loads in by hand.`);
    else if (c.loaded.has(f) && (confidence[f] === 'low' || confidence[f] === 'none')) warnings.push(`${f} e1RM is based on little data: check these loads`);
  }

  const block = {
    id: `b${o.blockNumber}`, number: o.blockNumber, name: o.name ?? `Block ${o.blockNumber} ${title(focus)}`,
    goal: focus === 'specialise' ? `Bring up the ${o.emphasis} while the other lifts keep ticking over.` : GOALS[focus],
    instructions: INSTRUCTIONS, weeks: weekList,
    generated: {
      at: new Date(o.now()).toISOString(), focus, weeks, daysPerWeek: days.length, progression: o.progression, rotate: o.rotate,
      seed: o.seed, deloadWeek: o.deloadWeek, fromBlock: template.fromBlock ?? null, athleteAsOf: athlete.asOf ?? null,
      e1rmStart, confidence, emphasis: o.emphasis, layoffWeeks: focus === 'return' ? o.layoffWeeks : null,
      checkIn: focus === 'maintenance' ? o.checkIn : null, deadliftStance: o.deadliftStance,
    },
  };
  return { block, rationale: [...blockRationale(o, c, slots, athlete), ...lines], warnings, volume: { perWeek, typical } };
}

/**
 * Re-load the planned sets not yet done from `fromWeek` on with a newer AthleteModel. Accessories, completed sets
 * and families without a known e1RM are left alone. Loads move only when they change by at least 2.5 kg.
 * @returns {{ block, changes: { week, day, exerciseId, setIndex, from, to }[] }}
 */
export function reviseBlock({ block, athlete, fromWeek } = {}) { // `catalogue` is accepted by the documented signature but not needed
  if (!block || !Array.isArray(block.weeks) || !block.generated) fail('block must be a block made by generateBlock');
  if (!athlete || !athlete.lifts || typeof athlete.lifts !== 'object') fail('athlete is required (from buildAthleteModel)');
  if (!Number.isInteger(fromWeek) || fromWeek < 1) fail('fromWeek must be a positive integer');
  const { progression, focus, deloadWeek, weeks: n, layoffWeeks } = block.generated;
  const g = drift(progression, focus);
  // A return block keeps its ramp back to 100% (it is relative to the block, not to the week revision starts at).
  const proj = (e1, w) => (focus === 'return'
    ? projectedE1rm(e1, progression, focus, w, { weeks: n, layoffWeeks: Number.isInteger(layoffWeeks) ? layoffWeeks : 4 })
    : e1 * (1 + g) ** (w - fromWeek));
  const out = structuredClone(block);
  const changes = [];
  for (const week of out.weeks) for (const day of week.days ?? []) for (const entry of day.entries ?? []) for (const set of entry.sets ?? []) {
    const gen = set.gen;
    if (!gen || set.completed || !(gen.week >= fromWeek) || gen.kind === 'accessory') continue;
    const e1 = e1rmOf(athlete, gen.family);
    if (e1 == null) continue;
    const deload = deloadWeek === 'all' || (deloadWeek === 'last' && gen.week === n);
    const e = gen.exposure === 'secondary' ? (focus === 'return' ? proj(e1, 1) : e1) : proj(e1, deload ? Math.max(focus === 'return' ? 1 : fromWeek, gen.week - 1) : gen.week);
    const base = unrounded(e, gen.reps, gen.rpe, biasOf(athlete, gen.family), gen.k, e1);
    if (base == null) continue;
    gen.e1rmRef = round1(e);
    const to = settle(base * (gen.kind === 'backoff' ? 1 - 0.03 * (set.index - 1) : 1), ceilingKg(e1, gen.reps));
    const from = set.load ? toKg(set.load) : null;
    if (from !== null && Math.abs(to - from) < 2.5) continue;
    set.load = { value: to, unit: 'kg', raw: String(to) };
    changes.push({ week: week.number, day: day.number, exerciseId: entry.exerciseId, setIndex: set.index, from, to });
  }
  return { block: out, changes };
}
